---
- hosts: aws

  vars_files:
    - ./vars/vars.yml

  vars:
    # Ansistrano vars
    ansistrano_deploy_to: "{{ project_deploy_dir }}" # Base path to deploy to.
    ansistrano_deploy_via: git # Method used to deliver the code to the server. Options are copy, rsync, git, svn, s3 or download

    # Variables used in the Git deployment strategy
    ansistrano_git_repo: "https://github.com/knpuniversity/ansible.git" # Location of the git repository
    ansistrano_git_branch: master # What version of the repository to check out. This can be the full 40-character SHA-1 hash, the literal string HEAD, a branch name, or a tag name

  roles:
    - carlosbuenosvinos.ansistrano-deploy
